application: APPENGINEID
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /table
  static_files: static/table.html
  upload: static/table.html

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /putData
  script: useData.application

- url: /getData
  script: useData.application
